module.exports = {
    CAT_EDIT: 'CAT_EDIT',
    CAT_EDIT_CANCEL: 'CAT_EDIT_CANCEL',
    CAT_SAVE: 'CAT_SAVE',
    CAT_DELETE: 'CAT_DELETE',
    CATS_INDEX: 'CATS_INDEX',
    HANDLE_CATS_INDEX: 'HANDLE_CATS_INDEX',
    CAT_CREATED: 'CAT_CREATED'
};